# https://ruszkow.ski/posts/2019-10-21-travis-+-pyinstaller-+-github-releases/
# https://docs.travis-ci.com/user/reference/windows
# https://chocolatey.org/packages/python

os: windows
language: shell

before_install:
  - choco install python --version=3.9
  - python -m pip install --upgrade pip

env: PATH=/c/Python39:/c/Python39/Scripts:$PATH

install:
  - pip install -r requirements.txt
  - pip install pyinstaller

before_deploy:
  - python build.py

deploy:
  provider: releases
  api_key: $RELEASE_TOKEN
  file_glob: true
  file: parkybot.zip
  skip_cleanup: true
  draft: true
  on:
    tags: true
  name: $TRAVIS_TAG
